package providers

// OfficialProviderModels maps all known 9router provider IDs to their official model list.
var OfficialProviderModels = map[string][]string{
	"alicode-intl": {
		"qwen3.5-plus",
		"kimi-k2.5",
		"glm-5",
		"MiniMax-M2.5",
		"qwen3-coder-next",
		"qwen3-coder-plus",
		"glm-4.7",
	},
	"alicode": {
		"qwen3.5-plus",
		"kimi-k2.5",
		"glm-5",
		"MiniMax-M2.5",
		"qwen3-max-2026-01-23",
		"qwen3-coder-next",
		"qwen3-coder-plus",
		"glm-4.7",
	},
	"alims-intl": {
		"qwen3.5-plus",
		"kimi-k2.5",
		"glm-5",
		"MiniMax-M2.5",
		"qwen3-coder-next",
		"qwen3-coder-plus",
		"glm-4.7",
	},
	"anthropic": {
		"claude-sonnet-4-20250514",
		"claude-opus-4-20250514",
		"claude-3-5-sonnet-20241022",
	},
	"antigravity": {
		"gemini-3.8-flash-high",
		"gemini-3.8-flash-medium",
		"gemini-3.8-flash-low",
		"gemini-3.8-flash",
		"gemini-3.7-flash-high",
		"gemini-3.7-flash-medium",
		"gemini-3.7-flash-low",
		"gemini-3.7-flash",
		"gemini-3.6-flash-high",
		"gemini-3.6-flash-medium",
		"gemini-3.6-flash-low",
		"gemini-3.5-flash-high",
		"gemini-3-flash-agent",
		"gemini-3.5-flash-low",
		"gemini-3.5-flash-extra-low",
		"gemini-pro-agent",
		"gemini-3.1-pro-low",
		"claude-sonnet-4-6",
		"claude-opus-4-6-thinking",
		"claude-3-7-sonnet",
		"claude-3-5-sonnet",
		"gpt-oss-120b-medium",
		"gemini-3-flash",
		"gemini-3.1-flash-image",
	},
	"api-airforce": {
		"anthropic/claude-3.7-sonnet",
		"moonshot/kimi-k2.6",
		"google/gemini-2.5-flash",
	},
	"assemblyai": {
		"universal-3-pro",
	},
	"aws-polly": {
		"standard",
		"neural",
		"long-form",
		"generative",
	},
	"baidu": {
		"deepseek-v4-pro",
		"deepseek-v4-flash",
		"glm-5.2",
		"glm-5.1",
		"kimi-k2.6",
		"qwen3.5-397b-a17b",
		"qwen3.5-27b",
	},
	"bazaarlink": {
		"auto:free",
		"claude-opus-4.7",
		"claude-sonnet-4.6",
		"claude-haiku-4.5",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.4-mini",
		"gpt-5.4-nano",
		"grok-4.3",
		"grok-4.20",
		"gemini-3.1-pro-preview",
		"gemini-3-flash-preview",
		"gemini-3.1-flash-lite-preview",
		"kimi-k2.6",
		"kimi-k2.5",
		"glm-5.1",
		"glm-5",
		"mimo-v2.5-pro",
		"mimo-v2.5",
		"minimax-m3",
		"minimax-m2.7",
		"minimax-m2.5",
		"qwen3.6-plus",
		"nemotron-3-super-120b-a12b",
	},
	"black-forest-labs": {
		"flux-pro-1.1",
	},
	"blackbox": {
		"claude-fable-5",
		"claude-opus-4.8",
		"claude-sonnet-4.6",
		"gpt-5.5",
		"gpt-5.4-pro",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-nano",
		"deepseek-v4-flash",
		"grok-4.3",
	},
	"bluesminds": {
		"gpt-4.1",
		"gpt-4.1-mini",
		"gpt-4.1-nano",
		"claude-sonnet-4-5",
		"claude-haiku-4-5",
		"gemini-2.0-flash",
		"gemini-2.0-flash-exp",
		"qwen-turbo",
		"kimi-k2",
		"kimi-k2-thinking",
		"glm-4.7",
		"minimax-m2.5",
		"claude-opus-4-5",
		"gemini-2.5-pro",
	},
	"byteplus": {
		"seed-2-0-pro-260328",
		"seed-2-0-code-preview-260328",
		"seed-2-0-mini-260215",
		"seed-2-0-lite-260228",
		"kimi-k2-thinking-251104",
		"glm-4-7-251222",
		"gpt-oss-120b-250805",
	},
	"cartesia": {
		"sonic-2",
		"sonic-3",
	},
	"cerebras": {
		"gpt-oss-120b",
		"zai-glm-4.7",
		"llama-3.3-70b",
		"llama-4-scout-17b-16e-instruct",
		"qwen-3-235b-a22b-instruct-2507",
		"qwen-3-32b",
	},
	"claude": {
		"claude-opus-5",
		"claude-fable-5",
		"claude-sonnet-5",
		"claude-haiku-4-5-20251001",
	},
	"cline": {
		"anthropic/claude-opus-4.7",
		"anthropic/claude-sonnet-4.6",
		"anthropic/claude-opus-4.6",
		"openai/gpt-5.3-codex",
		"openai/gpt-5.4",
		"google/gemini-3.1-pro-preview",
		"google/gemini-3.1-flash-lite-preview",
		"kwaipilot/kat-coder-pro",
	},
	"clinepass": {
		"cline-pass/glm-5.2",
		"cline-pass/kimi-k2.7-code",
		"cline-pass/kimi-k2.6",
		"cline-pass/deepseek-v4-pro",
		"cline-pass/deepseek-v4-flash",
		"cline-pass/mimo-v2.5",
		"cline-pass/mimo-v2.5-pro",
		"cline-pass/minimax-m3",
		"cline-pass/qwen3.7-max",
		"cline-pass/qwen3.7-plus",
	},
	"cloudflare-ai": {
		"@cf/meta/llama-3.2-1b-instruct",
		"@cf/meta/llama-3.2-3b-instruct",
		"@cf/meta/llama-3.1-8b-instruct-fp8-fast",
		"@cf/meta/llama-3.1-8b-instruct-awq",
		"@cf/mistralai/mistral-small-3.1-24b-instruct",
		"@cf/meta/llama-3.1-70b-instruct-fp8-fast",
		"@cf/meta/llama-3.3-70b-instruct-fp8-fast",
		"@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
		"@cf/moonshotai/kimi-k2.5",
		"@cf/moonshotai/kimi-k2.6",
		"@cf/zai-org/glm-4.7-flash",
		"@cf/qwen/qwq-32b",
		"@cf/qwen/qwen2.5-coder-32b-instruct",
		"@cf/black-forest-labs/flux-2-klein-9b",
	},
	"codebuddy-cn": {
		"glm-5.2",
		"glm-5.1",
		"glm-5.0",
		"glm-5.0-turbo",
		"glm-5v-turbo",
		"glm-4.7",
		"minimax-m3",
		"minimax-m2.7",
		"kimi-k2.7",
		"kimi-k2.6",
		"kimi-k2.5",
		"hy3-preview",
		"deepseek-v4-pro",
		"deepseek-v4-flash",
		"deepseek-v3-2-volc",
	},
	"codebuddy-intl": {
		"glm-5.2",
		"glm-5.1",
		"glm-5.0",
		"glm-5.0-turbo",
		"glm-5v-turbo",
		"glm-4.7",
		"minimax-m3",
		"minimax-m2.7",
		"kimi-k2.7",
		"kimi-k2.6",
		"kimi-k2.5",
		"hy3-preview",
		"deepseek-v4-pro",
		"deepseek-v4-flash",
		"deepseek-v3-2-volc",
	},
	"codex": {
		"gpt-5.6-sol",
		"gpt-5.6-sol-review",
		"gpt-5.6-terra",
		"gpt-5.6-terra-review",
		"gpt-5.6-luna",
		"gpt-5.6-luna-review",
		"gpt-5.5",
		"gpt-5.5-review",
		"gpt-5.4",
		"gpt-5.4-review",
		"gpt-5.4-mini",
		"gpt-5.4-mini-review",
		"gpt-5.3-codex-spark",
		"gpt-5.3-codex-spark-review",
		"gpt-5.5-image",
	},
	"cohere": {
		"command-r-plus-08-2024",
		"command-r-08-2024",
		"command-a-03-2025",
	},
	"comfyui": {
		"flux-dev",
	},
	"commandcode": {
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"stepfun/Step-3.5-Flash",
	},
	"coqui": {
		"tts_models/en/ljspeech/tacotron2-DDC",
	},
	"cursor": {
		"default",
		"claude-4.5-opus-high-thinking",
		"claude-4.5-opus-high",
		"claude-4.5-sonnet-thinking",
		"claude-4.5-sonnet",
		"claude-4.5-haiku",
		"claude-4.5-opus",
		"gpt-5.2-codex",
		"claude-4.6-opus-max",
		"claude-4.6-sonnet-medium-thinking",
		"kimi-k2.5",
		"gemini-3-flash-preview",
		"gpt-5.2",
		"gpt-5.3-codex",
	},
	"deepgram": {
		"nova-3",
	},
	"deepseek": {
		"deepseek-v4-pro",
		"deepseek-v4-pro-max",
		"deepseek-v4-pro-none",
		"deepseek-v4-flash",
		"deepseek-chat",
		"deepseek-reasoner",
	},
	"devin-cli": {
		"swe-1.6-fast",
		"swe-1.6",
		"swe-1.5-fast",
		"swe-1.5",
		"claude-opus-4.7-max",
		"claude-opus-4.7-high",
		"claude-opus-4.7-medium",
		"claude-opus-4.7-low",
		"claude-sonnet-4.6-thinking-1m",
		"claude-sonnet-4.6-thinking",
		"claude-sonnet-4.6",
		"claude-opus-4.6-thinking",
		"claude-opus-4.6",
		"claude-sonnet-4.5",
		"claude-haiku-4.5",
		"gpt-5.5-xhigh",
		"gpt-5.5-high",
		"gpt-5.5-medium",
		"gpt-5.5-low",
		"gpt-5.4-high",
		"gpt-5.4-medium",
		"gpt-5.4-low",
		"gpt-5.3-codex-high",
		"gpt-5.3-codex-medium",
		"gpt-5.3-codex-low",
		"gpt-5.2-high",
		"gpt-5.2-medium",
		"gpt-5.2-low",
		"gemini-3.1-pro-high",
		"gemini-3.1-pro-low",
		"gemini-3.0-flash-high",
		"gemini-2.5-pro",
		"deepseek-v4",
		"kimi-k2.6",
		"glm-5.1",
	},
	"elevenlabs": {
		"eleven_multilingual_v2",
		"eleven_turbo_v2_5",
	},
	"fal-ai": {
		"fal-ai/flux/schnell",
	},
	"featherless": {
		"deepseek-ai/DeepSeek-V4-Pro",
		"deepseek-ai/DeepSeek-V4-Flash",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.1",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
	},
	"fireworks": {
		"accounts/fireworks/models/deepseek-v3p1",
		"accounts/fireworks/models/llama-v3p3-70b-instruct",
		"accounts/fireworks/models/qwen3-235b-a22b",
		"nomic-ai/nomic-embed-text-v1.5",
	},
	"gemini-cli": {
		"gemini-3.1-pro-preview",
		"gemini-3-pro-preview",
		"gemini-3-flash-preview",
		"gemini-3.1-flash-lite-preview",
		"gemini-2.5-pro",
		"gemini-2.5-flash",
		"gemini-2.5-flash-lite",
	},
	"gemini": {
		"gemini-3.6-flash",
		"gemini-3.5-flash-lite",
		"gemini-3.1-pro-preview",
		"gemini-3.1-flash-lite-preview",
		"gemini-3-flash-preview",
		"gemini-2.5-pro",
		"gemini-2.5-flash",
		"gemini-2.5-flash-lite",
		"gemma-4-31b-it",
		"gemini-embedding-2-preview",
		"gemini-embedding-001",
		"text-embedding-005",
		"text-embedding-004",
		"gemini-3.1-flash-image-preview",
	},
	"github": {
		"gpt-5.2",
		"gpt-5.2-codex",
		"gpt-5.3-codex",
		"gpt-5.4",
		"gpt-5.4-mini",
		"claude-haiku-4.5",
		"claude-opus-4.5",
		"claude-sonnet-4.5",
		"claude-sonnet-4.6",
		"claude-opus-4.6",
		"claude-opus-4.7",
		"gemini-2.5-pro",
		"gemini-3-flash-preview",
		"gemini-3.1-pro-preview",
		"grok-code-fast-1",
		"oswe-vscode-prime",
		"goldeneye-free-auto",
		"text-embedding-3-small",
		"text-embedding-3-large",
	},
	"glm-cn": {
		"glm-5.2",
		"glm-5.1",
		"glm-5",
		"glm-4.7",
		"glm-4.6",
		"glm-4.5-air",
	},
	"glm": {
		"glm-5.2",
		"glm-5.1",
		"glm-5",
		"glm-4.7",
		"glm-4.6v",
	},
	"grok-cli": {
		"grok-4.5",
		"grok-4.5-high",
		"grok-4.5-medium",
		"grok-4.5-low",
	},
	"grok-web": {
		"grok-3",
		"grok-3-mini",
		"grok-3-thinking",
		"grok-4",
		"grok-4-mini",
		"grok-4-thinking",
		"grok-4-heavy",
		"grok-4.1-mini",
		"grok-4.1-fast",
		"grok-4.1-expert",
		"grok-4.1-thinking",
		"grok-4.2",
	},
	"groq": {
		"llama-3.3-70b-versatile",
		"meta-llama/llama-4-maverick-17b-128e-instruct",
		"qwen/qwen3-32b",
		"openai/gpt-oss-120b",
		"whisper-large-v3",
	},
	"huggingface": {
		"black-forest-labs/FLUX.1-schnell",
	},
	"hyperbolic": {
		"Qwen/QwQ-32B",
		"deepseek-ai/DeepSeek-R1",
		"deepseek-ai/DeepSeek-V3",
		"meta-llama/Llama-3.3-70B-Instruct",
		"meta-llama/Llama-3.2-3B-Instruct",
		"Qwen/Qwen2.5-72B-Instruct",
		"Qwen/Qwen2.5-Coder-32B-Instruct",
		"NousResearch/Hermes-3-Llama-3.1-70B",
	},
	"iflow": {
		"qwen3-coder-plus",
		"qwen3-max",
		"qwen3-vl-plus",
		"qwen3-max-preview",
		"qwen3-235b",
		"qwen3-235b-a22b-instruct",
		"qwen3-235b-a22b-thinking-2507",
		"qwen3-32b",
		"kimi-k2",
		"deepseek-v3.2",
		"deepseek-v3.1",
		"deepseek-v3",
		"deepseek-r1",
		"glm-4.7",
		"iflow-rome-30ba3b",
	},
	"inworld": {
		"inworld-tts-1.5-mini",
		"inworld-tts-1.5-max",
	},
	"jina-ai": {
		"jina-embeddings-v3",
		"jina-embeddings-v2-base-en",
		"jina-embeddings-v2-base-code",
	},
	"kilo-gateway": {
		"kilo-auto/free",
		"nvidia/nemotron-3-super-120b-a12b:free",
		"nvidia/nemotron-3-ultra-550b-a55b:free",
		"kwaipilot/kat-coder-pro-v2.5:free",
		"kilo-auto/frontier",
		"kilo-auto/balanced",
	},
	"kilocode": {
		"anthropic/claude-sonnet-4-20250514",
		"anthropic/claude-opus-4-20250514",
		"google/gemini-2.5-pro",
		"google/gemini-2.5-flash",
		"openai/gpt-4.1",
		"openai/o3",
		"deepseek/deepseek-chat",
		"deepseek/deepseek-reasoner",
	},
	"kimchi": {
		"minimax-m3",
		"kimi-k2.7",
		"kimi-k2.6",
		"kimi-k2.5",
		"nemotron-3-ultra-fp4",
		"minimax-m2.7",
		"claude-opus-4-6",
		"claude-sonnet-4-6",
	},
	"kimi": {
		"kimi-k3",
		"k3",
		"kimi-for-coding",
		"kimi-for-coding-highspeed",
		"kimi-k2.7-code",
		"kimi-k2.7-code-highspeed",
		"kimi-k2.6",
		"kimi-k2.5",
		"kimi-k2.5-thinking",
		"kimi-latest",
	},
	"kiro": {
		"claude-opus-5",
		"claude-opus-5-thinking",
		"claude-opus-5-agentic",
		"claude-opus-5-thinking-agentic",
		"claude-opus-4.8",
		"claude-opus-4.8-thinking",
		"claude-opus-4.8-agentic",
		"claude-opus-4.8-thinking-agentic",
		"claude-opus-4.7",
		"claude-opus-4.7-thinking",
		"claude-opus-4.7-agentic",
		"claude-opus-4.7-thinking-agentic",
		"claude-opus-4.5",
		"claude-opus-4.5-thinking",
		"claude-opus-4.5-agentic",
		"claude-opus-4.5-thinking-agentic",
		"claude-sonnet-5",
		"claude-sonnet-4.5",
		"claude-haiku-4.5",
		"deepseek-3.2",
	},
	"llm7": {
		"gpt-5.5",
		"claude-opus-5",
		"deepseek-v4-flash",
		"grok-4.5",
		"kimi-k3",
	},
	"mimo-free": {
		"mimo-auto",
	},
	"minimax-cn": {
		"MiniMax-M3",
		"MiniMax-M2.7",
		"MiniMax-M2.5",
		"MiniMax-M2.1",
		"speech-2.8-hd",
		"speech-2.8-turbo",
		"speech-2.6-hd",
		"speech-2.6-turbo",
		"speech-02-hd",
		"speech-02-turbo",
		"speech-01-hd",
		"speech-01-turbo",
	},
	"minimax": {
		"MiniMax-M3",
		"MiniMax-M2.7",
		"MiniMax-M2.5",
		"MiniMax-M2.1",
		"minimax-image-01",
	},
	"mistral": {
		"mistral-large-latest",
		"codestral-latest",
		"mistral-medium-latest",
		"mistral-embed",
	},
	"mmf": {
		"mimo-auto",
	},
	"morph": {
		"morph-v3-large",
		"morph-v3-fast",
		"morph-qwen35-397b",
		"morph-minimax27-230b",
		"morph-qwen36-27b",
		"morph-dsv4flash",
	},
	"nanobanana": {
		"nanobanana-flash",
	},
	"nebius": {
		"meta-llama/Llama-3.3-70B-Instruct",
		"Qwen/Qwen3-Embedding-8B",
	},
	"nvidia": {
		"minimaxai/minimax-m2.7",
		"minimaxai/minimax-m3",
		"z-ai/glm-5.2",
		"deepseek-ai/deepseek-v4-pro",
		"deepseek-ai/deepseek-v4-flash",
		"moonshotai/kimi-k2.6",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"nvidia/nv-embedqa-e5-v5",
		"nvidia/parakeet-ctc-1.1b-asr",
	},
	"ollama": {
		"gpt-oss:120b",
		"kimi-k2.5",
		"glm-5",
		"minimax-m2.5",
		"glm-4.7-flash",
		"qwen3.5",
		"minimax-m3",
	},
	"openai": {
		"gpt-5.4",
		"gpt-5.4-mini",
		"gpt-5.4-nano",
		"gpt-5.2",
		"gpt-5.1",
		"gpt-5",
		"gpt-5-mini",
		"gpt-5-nano",
		"gpt-4o",
		"gpt-4o-mini",
		"gpt-4-turbo",
		"gpt-4.1",
		"gpt-4.1-mini",
		"gpt-4.1-nano",
		"o3",
		"o3-mini",
		"o3-pro",
		"o4-mini",
		"o1",
		"o1-mini",
		"text-embedding-3-large",
		"text-embedding-3-small",
		"text-embedding-ada-002",
		"tts-1",
		"tts-1-hd",
		"gpt-4o-mini-tts",
		"whisper-1",
	},
	"opencode-go": {
		"glm-5.2",
		"glm-5.1",
		"kimi-k2.7-code",
		"kimi-k2.6",
		"deepseek-v4-pro",
		"deepseek-v4-flash",
		"mimo-v2.5",
		"mimo-v2.5-pro",
		"minimax-m3",
		"minimax-m2.7",
		"minimax-m2.5",
		"qwen3.7-max",
		"qwen3.7-plus",
		"qwen3.6-plus",
	},
	"opencode": {
		"big-pickle",
		"mimo-v2.5-free",
		"ling-3.0-flash-fin-free",
		"nemotron-3-ultra-free",
		"nemotron-3.5-lightning-free",
		"laguna-s-2.1-free",
		"deepseek-v4-flash-free",
	},
	"openrouter": {
		"openai/text-embedding-3-large",
		"openai/text-embedding-3-small",
		"openai/text-embedding-ada-002",
		"qwen/qwen3-embedding-8b",
		"perplexity/pplx-embed-v1-4b",
		"perplexity/pplx-embed-v1-0.6b",
		"nvidia/llama-nemotron-embed-vl-1b-v2:free",
		"openai/gpt-4o-mini-tts",
		"openai/tts-1-hd",
		"openai/tts-1",
		"openai/dall-e-3",
	},
	"perplexity-agent": {
		"perplexity/sonar",
		"openai/gpt-5.5",
		"openai/gpt-5.4",
		"openai/gpt-5.4-mini",
		"anthropic/claude-sonnet-4-6",
		"anthropic/claude-opus-4-8",
		"google/gemini-3.1-pro-preview",
		"xai/grok-4.20-reasoning",
		"perplexity/glm-5.2",
		"perplexity/kimi-k2.7-code",
		"nvidia/nemotron-3-super-120b-a12b",
	},
	"perplexity-web": {
		"pplx-auto",
		"pplx-sonar",
		"pplx-gpt",
		"pplx-gemini",
		"pplx-sonnet",
		"pplx-opus",
		"pplx-nemotron",
	},
	"perplexity": {
		"sonar-pro",
		"sonar",
	},
	"playht": {
		"PlayDialog",
		"Play3.0-mini",
	},
	"poolside": {
		"poolside/laguna-s-2.1",
		"poolside/laguna-xs-2.1",
	},
	"qoder": {
		"ultimate",
		"auto",
		"performance",
		"efficient",
		"qmodel_preview",
		"qmodel_latest",
		"qmodel",
		"kmodel_latest",
		"kmodel",
		"gm51model",
		"dmodel",
		"dfmodel",
		"mmodel",
	},
	"qwen": {
		"qwen3-coder-plus",
		"qwen3-coder-flash",
		"vision-model",
		"coder-model",
	},
	"recraft": {
		"recraftv3",
	},
	"runwayml": {
		"gen4_image",
	},
	"sambanova": {
		"MiniMax-M2.7",
	},
	"sdwebui": {
		"stable-diffusion-v1-5",
	},
	"siliconflow": {
		"deepseek-ai/DeepSeek-V4-Pro",
		"deepseek-ai/DeepSeek-V4-Flash",
		"deepseek-ai/DeepSeek-V3.2",
		"deepseek-ai/DeepSeek-V3.2-Exp",
		"deepseek-ai/DeepSeek-V3.1",
		"deepseek-ai/DeepSeek-V3.1-Terminus",
		"deepseek-ai/DeepSeek-R1",
		"Qwen/Qwen3.5-397B-A17B",
		"Qwen/Qwen3.5-122B-A10B",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"openai/gpt-oss-120b",
		"MiniMaxAI/MiniMax-M2.5",
		"inclusionAI/Ling-flash-2.0",
	},
	"stability-ai": {
		"stable-image-ultra",
	},
	"tencent": {
		"hunyuan-turbos-latest",
		"hunyuan-t1-latest",
	},
	"together": {
		"meta-llama/Llama-3.3-70B-Instruct-Turbo",
		"deepseek-ai/DeepSeek-R1",
		"Qwen/Qwen3-235B-A22B",
		"meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
		"BAAI/bge-large-en-v1.5",
		"togethercomputer/m2-bert-80M-8k-retrieval",
	},
	"tortoise": {
		"tortoise-v2",
	},
	"trae": {
		"auto",
		"work",
		"gemini-3.1-pro",
		"gemini-3-flash-solo",
		"minimax-m3",
		"minimax-m2.7",
		"kimi-k2.5",
		"gpt-5.4",
		"gpt-5.2",
	},
	"venice": {
		"venice-uncensored-1-2",
		"zai-org-glm-5",
		"qwen3-235b-a22b-instruct-2507",
		"qwen3-coder-480b-a35b-instruct-turbo",
		"qwen3-vl-235b-a22b",
		"deepseek-v4-pro",
		"llama-3.3-70b",
		"hermes-3-llama-3.1-405b",
		"mistral-small-3-2-24b-instruct",
		"text-embedding-3-large",
		"text-embedding-bge-m3",
		"text-embedding-qwen3-8b",
		"venice-sd35",
	},
	"vertex-partner": {
		"deepseek-ai/deepseek-v3.2-maas",
		"qwen/qwen3-next-80b-a3b-thinking-maas",
		"qwen/qwen3-next-80b-a3b-instruct-maas",
		"zai-org/glm-5-maas",
	},
	"vertex": {
		"gemini-3.1-pro-preview",
		"gemini-3.1-flash-lite-preview",
		"gemini-3-flash-preview",
		"gemini-2.5-flash",
	},
	"volcengine-ark": {
		"Doubao-Seed-2.0-Code",
		"Doubao-Seed-2.0-pro",
		"Doubao-Seed-2.0-lite",
		"Doubao-Seed-Code",
		"DeepSeek-V4-Flash",
		"DeepSeek-V4-Pro",
		"GLM-5.1",
		"MiniMax-M2.7",
		"Kimi-K2.6",
	},
	"voyage-ai": {
		"voyage-3-large",
		"voyage-3.5",
		"voyage-3.5-lite",
		"voyage-code-3",
		"voyage-finance-2",
		"voyage-law-2",
		"voyage-multilingual-2",
	},
	"windsurf": {
		"swe-1.6-fast",
		"swe-1.6",
		"swe-1.5-fast",
		"swe-1.5",
		"claude-opus-4.7-max",
		"claude-opus-4.7-xhigh",
		"claude-opus-4.7-high",
		"claude-opus-4.7-medium",
		"claude-opus-4.7-low",
		"claude-opus-4.7-review",
		"claude-sonnet-4.6-thinking-1m",
		"claude-sonnet-4.6-1m",
		"claude-sonnet-4.6-thinking",
		"claude-sonnet-4.6",
		"claude-opus-4.6-thinking",
		"claude-opus-4.6",
		"claude-opus-4.5-thinking",
		"claude-opus-4.5",
		"claude-sonnet-4.5-thinking",
		"claude-sonnet-4.5",
		"claude-haiku-4.5",
		"gpt-5.5-xhigh-fast",
		"gpt-5.5-xhigh",
		"gpt-5.5-high-fast",
		"gpt-5.5-high",
		"gpt-5.5-medium-fast",
		"gpt-5.5-medium",
		"gpt-5.5-low-fast",
		"gpt-5.5-low",
		"gpt-5.5-none-fast",
		"gpt-5.5-none",
		"gpt-5.4-xhigh-fast",
		"gpt-5.4-xhigh",
		"gpt-5.4-high-fast",
		"gpt-5.4-high",
		"gpt-5.4-medium-fast",
		"gpt-5.4-medium",
		"gpt-5.4-low-fast",
		"gpt-5.4-low",
		"gpt-5.4-none-fast",
		"gpt-5.4-none",
		"gpt-5.4-mini-xhigh",
		"gpt-5.4-mini-high",
		"gpt-5.4-mini-medium",
		"gpt-5.4-mini-low",
		"gpt-5.3-codex-xhigh-fast",
		"gpt-5.3-codex-xhigh",
		"gpt-5.3-codex-high-fast",
		"gpt-5.3-codex-high",
		"gpt-5.3-codex-medium-fast",
		"gpt-5.3-codex-medium",
		"gpt-5.3-codex-low-fast",
		"gpt-5.3-codex-low",
		"gpt-5.2-xhigh",
		"gpt-5.2-high",
		"gpt-5.2-medium",
		"gpt-5.2-low",
		"gpt-5.2-none",
		"gpt-5",
		"gpt-4.1",
		"gpt-4.1-mini",
		"gpt-4.1-nano",
		"gpt-4o",
		"gpt-4o-mini",
		"gemini-3.1-pro-high",
		"gemini-3.1-pro-low",
		"gemini-3.0-flash-high",
		"gemini-3.0-flash-medium",
		"gemini-3.0-flash-low",
		"gemini-3.0-flash-minimal",
		"gemini-2.5-pro",
		"deepseek-v4",
		"kimi-k2.6",
		"kimi-k2.5",
		"glm-5.1",
	},
	"xai": {
		"grok-4",
		"grok-4-fast-reasoning",
		"grok-code-fast-1",
		"grok-3",
		"grok-2-image-1212",
	},
	"xiaomi-mimo": {
		"mimo-v2.5-pro",
		"mimo-v2.5",
		"mimo-v2-omni",
		"mimo-v2-flash",
	},
	"xiaomi-tokenplan": {
		"mimo-v2.5-pro",
		"mimo-v2.5-pro-claude",
		"mimo-v2.5",
		"mimo-v2-pro",
		"mimo-v2-omni",
		"mimo-v2-tts",
		"mimo-v2.5-tts",
		"mimo-v2.5-tts-voiceclone",
		"mimo-v2.5-tts-voicedesign",
	},
}

func init() {
	if gh, ok := OfficialProviderModels["github"]; ok {
		OfficialProviderModels["copilot"] = gh
	}
	if cx, ok := OfficialProviderModels["codex"]; ok {
		OfficialProviderModels["cx"] = cx
	}
	if ag, ok := OfficialProviderModels["antigravity"]; ok {
		OfficialProviderModels["ag"] = ag
	}
}

// GetOfficialModels returns the list of official models for a provider, or nil if not found.
func GetOfficialModels(provider string) []string {
	if m, ok := OfficialProviderModels[provider]; ok {
		return m
	}
	return nil
}
