(() => {
  'use strict';
  const control = window.__ZYROUTER_CONTROL_BASE__ || localStorage.getItem('zy_control_base') || (location.hostname === 'localhost' || location.hostname === '127.0.0.1' ? 'http://127.0.0.1:20128' : '');
  const inference = window.__ZYROUTER_API_BASE__ || localStorage.getItem('zy_api_base') || 'https://api.zyvenox.tech';
  let challenge = '', timer, source;
  const $ = (id) => document.getElementById(id);
  const api = async (path, options = {}) => fetch(`${control}${path}`, { ...options, credentials: 'include', headers: { ...(options.headers || {}) } });
  const show = (id) => document.querySelectorAll('.view').forEach(v => v.classList.toggle('hidden', v.id !== id));
  const fmt = (v) => Number(v || 0).toLocaleString('id-ID');
  function renderEvent(e) { const row = document.createElement('div'); row.innerHTML = `<b>${e.model || 'global-alias'}</b> · ${e.status || 'event'} · ${fmt(e.totalTokens || ((e.promptTokens || 0) + (e.completionTokens || 0)))} tok <small>${new Date(e.timestamp || Date.now()).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</small>`; $('logsList').prepend(row); while ($('logsList').children.length > 100) $('logsList').lastElementChild.remove(); }
  async function loadDashboard() { const [p,u,k] = await Promise.all([api('/api/user/profile'),api('/api/user/usage'),api('/api/user/key')]); if (!p.ok) throw Error('Session client belum aktif'); const pd=await p.json(), ud=await u.json(), kd=await k.json(); $('profile').textContent=`${pd.user.displayName || ''} @${pd.user.telegramUsername || 'telegram-user'}`; $('myRequests').textContent=fmt(ud.totalRequests); $('myTokens').textContent=fmt(ud.totalTokens); $('keyInfo').textContent=kd.key ? `${kd.key.keyPrefix}...` : 'Belum ada key aktif'; $('modelsList').innerHTML=(pd.allowedAliases||[]).map(x=>`<div><b>${x}</b></div>`).join('') || '<div>Tidak ada alias aktif.</div>'; $('auth').classList.add('hidden'); $('app').classList.remove('hidden'); startGlobalStream(); }
  async function startVerification() { if (challenge) return; $('start').disabled=true; const res=await api('/api/user/verification/start',{method:'POST'}); if(!res.ok) throw Error('Gagal membuat verification challenge'); const d=await res.json(); challenge=d.challengeId; $('challenge').classList.remove('hidden'); $('code').textContent=challenge; let seconds=600; $('timer').textContent='10:00'; timer=setInterval(()=>{seconds--; $('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`; if(seconds<=0){clearInterval(timer);challenge='';$('start').disabled=false;$('challenge').classList.add('hidden')}},1000); const current=challenge; const poll=setInterval(async()=>{const r=await api(`/api/user/verification/${encodeURIComponent(current)}`); if(!r.ok)return; const v=await r.json(); if(v.status==='verified'){clearInterval(poll);clearInterval(timer);challenge='';await loadDashboard()}},2000); }
  function startGlobalStream(){ if(source)return; source=new EventSource(`${control}/api/user/global-usage/stream`,{withCredentials:true}); source.onopen=()=>$('streamState').textContent='LIVE'; source.onerror=()=>$('streamState').textContent='RECONNECTING'; source.onmessage=e=>{try{const d=JSON.parse(e.data);$('globalRequests').textContent=fmt(d.totalRequests);$('globalTokens').textContent=fmt(d.totalTokens);(d.recent||[]).forEach(renderEvent)}catch{}}; }
  async function keyAction(path,method){const r=await api(path,{method});const d=await r.json().catch(()=>({}));if(d.key){$('secret').textContent=d.key}await loadDashboard()}
  $('start').onclick=()=>startVerification().catch(e=>$('auth-error').textContent=e.message);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('generate').onclick=()=>keyAction('/api/user/key','POST');$('rotate').onclick=()=>keyAction('/api/user/key/rotate','POST');$('revoke').onclick=()=>keyAction('/api/user/key','DELETE');
  loadDashboard().catch(()=>{});
})();
